name: st_ai_impute
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=2.4.3
  - pandas=2.3.3
  - scipy=1.17.1
  - h5py=3.16.0
  - jupyterlab
  - matplotlib=3.10.8
  - scikit-learn=1.8.0
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pip:
      - anndata==0.12.10
